name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12", "pypy-3.9", "pypy-3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install .
          python -m pip install -r test_requirements.txt

      - name: Run unittests
        run: python -m pytest --cov-fail-under=90

      - name: Verify dependencies
        # Jinja, https://data.safetycli.com/v/70612/97c
        run: python -m safety check --ignore 70612

      - name: Verify code style
        run: python -m flake8 -v

      - name: Verify type annotations
        run: |
          python -m pip install mypy
          python -m mypy --config mypy.ini mollie/
